name: jEssMobsReBrain
version: 1.0
author: Kodek
main: jcraft.rebrain.ReBrainPlugin
load: STARTUP

permissions:
  mobsrebrain.spawn:
    default: op
    
commands:
  spawnentity:
    permission: mobsrebrain.spawn